ADD: Added support for tests using VirtualBox hypervisor ADD: Added support for web_create_user() to check that creating a new user through the web interface succeeded FIX: Added rudimentary precondition support for boot_check to verify that there is SSH access as root before checking for boot errors as this results in false reports of the test passing as there are no boot errors to find errors in FIX: Had to use literal quotes for regular expression as the \ and spaces for multi-line regular expressions were being interpreted literally when using double quotes (BASH syntactic sauerkraut again)
git-svn-id: http://cernvm-release-testing.googlecode.com/svn@52 e1b191a7-760c-b37a-3d11-b84f7cd3b9c7

diff --git a/trunk/tapper/tapper-autoreport/cernvm-testcases b/trunk/tapper/tapper-autoreport/cernvm-testcases
--- a/trunk/tapper/tapper-autoreport/cernvm-testcases
+++ b/trunk/tapper/tapper-autoreport/cernvm-testcases
@@ -43,21 +43,27 @@ check_ssh()
 check_boot_error()
 {
 	RESULT=0
-	BOOT_TESTS=("ssh root@$1 dmesg | egrep \"error|warning|fail\" > $2" 
-"ssh root@$1 cat /var/log/boot.log | egrep \"error|warning|fail\" >> $2" 
-"ssh root@$1 cat /var/log/messages | egrep \"error|warning|fail\" >> $2" 
-"ssh root@$1 cat /var/log/cernvm-update.log | egrep \"error|warning|fail\" >> $2")
+	BOOT_TESTS=("ssh -q -o \"BatchMode=yes\" root@$1 dmesg | egrep \"error|warning|fail\" > $2" 
+"ssh -q -o \"BatchMode=yes\" root@$1 cat /var/log/boot.log | egrep \"error|warning|fail\" >> $2" 
+"ssh -q -o \"BatchMode=yes\" root@$1 cat /var/log/messages | egrep \"error|warning|fail\" >> $2" 
+"ssh -q -o \"BatchMode=yes\" root@$1 cat /var/log/cernvm-update.log | egrep \"error|warning|fail\" >> $2")
 
+	# Precondition for ssh support as root for boot error tests
+	if check_ssh root $1 ; test "$?" -eq 0 ; then
 	for test in "${BOOT_TESTS[@]}"
 	do
 		eval $test
-		    # If one of the tests has boot error, set result as failure and break
+		    # If any of the tests has boot error, set result as failure and continue
+			# logging the rest of the boot messages that contain boot errors
 		    if [ "$?" -eq 0 ]
 		    then
 		            RESULT=1
-		            break
 		    fi
 	done
+	else
+		echo "FAIL - Precondition for ssh support as root for boot error tests"
+		RESULT=1
+	fi
 	
 	return $RESULT
 }
@@ -66,7 +72,7 @@ check_boot_error()
 # @param $1 - The IP address of the machine to login via ssh
 check_time()
 {
-	ssh root@$1 ps -eaf | grep -q ntpd
+	ssh -q -o "BatchMode=yes" root@$1 ps -eaf | grep -q ntpd
 
 	return $?
 }
diff --git a/trunk/tapper/tapper-autoreport/web-interface b/trunk/tapper/tapper-autoreport/web-interface
--- a/trunk/tapper/tapper-autoreport/web-interface
+++ b/trunk/tapper/tapper-autoreport/web-interface
@@ -17,7 +17,7 @@
 HEADER=('')
 # The base template http header used
 TEMPLATE_HEADER=(
-'Host: 192.168.122.252:8004' \
+'Host: 192.168.1.139:8004' \
 'User-Agent: Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.17) Gecko/20110428 Fedora/3.6.17-1.fc13 Firefox/3.6.17' \
 'Accept-Language: en-us,en;q=0.5' \
 'Accept-Encoding: gzip,deflate' \
@@ -87,14 +87,16 @@ web_check_login()
 	curl -i -v --cookie cjar --cookie-jar cjar "${HEADER[@]}" --data "user_name=$2" --data "password=$3" \
 	--data "login=Login" --location-trusted http://$1:8004/login > $4 2>&1
 
+	
 	# Check that curl didn't have any error return codes, then verify that it was
 	# was possible to login on the web interface by validating that curl was 
 	# redirected to the status page
 	RESULT=1
 	if [ "$?" -eq 0 ]
 	then
-		if grep -q -e "Location: http://$1:8004/status/Status/" $4 ; \
-		test "$?" -eq 0 && grep -q -e '<title>CernVM Software Appliance - Appliance Status</title>' \
+		if grep -q -e "HTTP/1.1 403 Forbidden" $4 ; test "$?" -eq 1 && grep -q \
+		-e "Location: http://$1:8004/status/Status/" $4 ; test "$?" -eq 0 && grep \
+		-q -e '<title>CernVM Software Appliance - Appliance Status</title>' \
 		$4 ; test "$?" -eq 0
 		then
 			RESULT=0
@@ -124,8 +126,21 @@ web_create_user()
 	"cernvmUserGroup=alice" --data "cernvmUserShell=%2Fbin%2Fbash" --data "newpass1=$3" \
 	--data "newpass2=$3" --location-trusted http://$1:8004/cernvm/User/userUpdate \
 	> $4 2>&1
+	
+	# Check that curl didn't have any error return codes, then verify that the
+	# new user created through the webinterface succeeded 
+	RESULT=1
+	if [ "$?" -eq 0 ]
+	then
+		if egrep -q '^\{\"message\"\:[[:space:]]*\"Completed[[:space:]]*Successfully\"\,
+		[[:space:]]*\"errors\"\:[[:space:]]*\[\]\,[[:space:]]*\"page\"\:[[:space:]]*\"\"\,
+		[[:space:]]*\"schedId\"\:[[:space:]]*[[:digit:]]*\}' $4 ; test "$?" -eq 0
+		then	
+			RESULT=0
+		fi
+	fi
 
-	return $?
+	return $RESULT
 }
 
 
@@ -147,14 +162,14 @@ web_restart()
 	curl -i -v --cookie cjar --cookie-jar cjar "${HEADER[@]}" --location-trusted \
 	http://$1:8004/reboot/Reboot/rebootNow > $2 2>&1
 
-	# Check that curl didn't have any error return codes, then verify that it was
-	# possible to restart the 
+	# Check that curl didn't have any error return codes, then verify that the
+	# webinterface restart succeeded 
 	RESULT=1
 	if [ "$?" -eq 0 ]
 	then
-		if egrep -q "^\{\"message\"\:[[:space:]]*\"Rebooting[[:space:]]*now\.\"\,\
-		[[:space:]]*\"errors\"\:[[:space:]]*\[\]\,[[:space:]]*\"schedId\"\:\
-		[[:space:]]*[[:digit:]]*\}" $2 ; test "$?" -eq 0
+		if egrep -q '^\{\"message\"\:[[:space:]]*\"Rebooting[[:space:]]*now\.\"\,
+		[[:space:]]*\"errors\"\:[[:space:]]*\[\]\,[[:space:]]*\"schedId\"\:
+		[[:space:]]*[[:digit:]]*\}' $2 ; test "$?" -eq 0
 		then
 			sleep 120
 			check_boot_error $1 $3
