SUMMARY: Added support to determine the MAC address automatically for VMware on both Linux and OS X systems
ADD: Added support to get_net_name() function to automatically determine the network name for VMware on both Linux and OS X systems
ADD: Added function get_mac_address() which returns the MAC address from the virtual machine definition, supports all hypervisors on both Linux and OS X
ADD: Added support to get_ip_address() function to automatically determine the IP address for VMware on both Linux and OS X systems

git-svn-id: http://cernvm-release-testing.googlecode.com/svn@150 e1b191a7-760c-b37a-3d11-b84f7cd3b9c7

diff --git a/trunk/tapper/tapper-autoreport/general-interface b/trunk/tapper/tapper-autoreport/general-interface
--- a/trunk/tapper/tapper-autoreport/general-interface
+++ b/trunk/tapper/tapper-autoreport/general-interface
@@ -133,8 +133,8 @@ get_os_name()
         OS_NAME="Windows"
         ;;
     *)
-       OS_NAME="Unknown"
-       ;;
+        OS_NAME="Unknown"
+        ;;
     esac
 
     echo "${OS_NAME}"
@@ -302,27 +302,73 @@ get_hash()
 # NAME
 #   get_net_name
 # DESCRIPTION
-#   Simple function that returns the network name from xml network definition file
+#   Simple function that returns the network name for a virtual machine
 # ARGUMENTS
-#   $1 - The network XML definition file
+#   $1 - The current hypervisor for the virtual machine network
+#   $2 - The network XML definition file, not applicable for VMware
 # RETURN VALUE
 #   networkname - The network name defined in the xml network definition file
 # RESULT
 #   exitstatus - Sets $? as a zero for success, otherwise sets an error code
 # EXAMPLE
-#   NET_NAME=$(get_net_name ./network-definition.xml)
+#   NET_NAME=$(get_net_name kvm ./network-definition.xml)
+#   NET_NAME=$(get_net_name vmware)
 #***
 get_net_name()
 {
+    NETNAME=""
     RESULT=1
     
-    # Network name not specified, set network name as default name in template
-    NET_NAME=$(egrep -E "^[[:space:]]*<name>.+</name>" $1 | \
-               sed -E "s|.*<name>(.*)</name>.*|\\1|")
+    if [ "$1" != "vmware" ]
+    then
+        if file_exists $2 ; test "$?" -eq 0 
+        then
+            # Set network name as default name in xml file
+            NETNAME=$(egrep -E "^[[:space:]]*<name>.+</name>" $2 | \
+                      sed -E "s|.*<name>(.*)</name>.*|\\1|")
+            RESULT=$?
+        fi
 
-    RESULT=$?
-    echo ${NET_NAME}
+    # Otherwise for vmware, network xml file not applicable, network name is vmnet1
+    else
+        NETNAME="vmnet1"
+        RESULT=0
+    fi
+
+    echo ${NETNAME}
     return $RESULT  
+}
+
+
+#****f* general-interface/get_mac_address
+# NAME
+#   get_mac_address
+# DESCRIPTION
+#   Simple function that returns the mac address from the virtual machine definition file
+# ARGUMENTS
+#   $1 - The virtual machine XML definition file
+# RETURN VALUE
+#   macaddress - The mac address defined in the xml definition file
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   MAC_ADDRESS=$(get_mac_address ./kvm-definition.xml)
+#***
+get_mac_address()
+{
+    MACADDRESS=""
+    RESULT=1
+    
+    if file_exists $1 ; test "$?" -eq 0
+    then
+        # Set the mac address as the value in xml file
+        MACADDRESS=$(egrep -E "^.*mac[[:space:]]*address='.*'" $1 | sed -E \
+                     "s|^.*mac[[:space:]]*address='(.*)'.*|\\1|")
+        RESULT=$?
+    fi
+
+    echo "${MACADDRESS}"
+    return $RESULT    
 }
 
 
@@ -330,26 +376,44 @@ get_net_name()
 # NAME
 #   get_ip_address
 # DESCRIPTION
-#   Simple function that returns the ip address from the xml network definition file
+#   Simple function that returns the ip address of a virtual machine
 # ARGUMENTS
-#   $1 - The network XML definition file
+#   $1 - The current hypervisor for the virtual machine network
+#   $2 - The MAC address of the virtual machine network connection
+#   $3 - The network XML definition file, not applicable for VMware
 # RETURN VALUE
 #   ipaddress - The ip address defined in the xml network definition file
 # RESULT
 #   exitstatus - Sets $? as a zero for success, otherwise sets an error code
 # EXAMPLE
-#   IP_ADDRESS=$(get_ip_address ./network-definition.xml)
+#   IP_ADDRESS=$(get_ip_address kvm 52:54:00:7B:30:75 ./network-definition.xml)
+#   IP_ADDRESS=$(get_ip_address vmware 00:50:56:C0:00:01)
 #***
 get_ip_address()
 {
+    MACADDRESS="$2"
+    IPADDRESS=""
     RESULT=1
-
-    # IP address not specified, set the ip address as default in template
-    IP_ADDRESS=$(egrep -E "^[[:space:]]*<range[[:space:]]*start='(.*)'" $1 | \
-                 sed -E "s|.*start='([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})'.*|\\1|")
     
-    RESULT=$?
-    echo ${IP_ADDRESS}
+    if [ "$1" != "vmware" ]
+    then
+        if file_exists $3 ; test "$?" -eq 0 
+        then
+            # Set the ip address as default in xml file
+            IPADDRESS=$(egrep -E "^[[:space:]]*<range[[:space:]]*start='(.*)'" $3 | sed -E \
+                        "s|.*start='([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})'.*|\\1|")
+            RESULT=$?
+        fi
+    # Otherwise for vmware, network xml file not applicable, determine the
+    # IP address of the virtual machine from the arp table
+    else
+        # Determine the IP address from the arp output
+        IPADDRESS=$(arp -an | grep -E "^.*${MACADDRESS}" | sed -E \
+                    "s|^.*\(([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})\).*|\\1|")
+        RESULT=$?
+    fi
+
+    echo "${IPADDRESS}"
     return $RESULT          
 }
 
