SUMMARY: Converted all scripts to work with an automatic documentation generator ROBODoc, so that an API reference can be easily generated in LaTeX and included into the developer manual
ADD: Added documentation in ROBODoc compliant format for all general-interface functions
ADD: Added documentation in ROBODoc compliant format for all virt-interface functions
ADD: Added documentation in ROBODoc compliant format for all web-interface functions
REMOVE: Removed old documentation and formatting for all general-interface functions
REMOVE: Removed old documentation and formatting for all virt-interface functions
REMOVE: Removed old documentation and formatting for all web-interface functions

git-svn-id: http://cernvm-release-testing.googlecode.com/svn@121 e1b191a7-760c-b37a-3d11-b84f7cd3b9c7

diff --git a/trunk/tapper/tapper-autoreport/general-interface b/trunk/tapper/tapper-autoreport/general-interface
--- a/trunk/tapper/tapper-autoreport/general-interface
+++ b/trunk/tapper/tapper-autoreport/general-interface
@@ -2,22 +2,36 @@
 
 # =============================================================================
 #
-# general-interface
-# -----------------
+#****** test-suite/general-interface
+# NAME
+#   general-interface
 #
-# This script contains general interface functions that interface with 
-# the host system and provide generic functionality such as checking the
-# host architecture, getting the host operating system, checking if a file
-# exists, etc.
+# DESCRIPTION
+#   This script contains general interface functions that interface with 
+#   the host system and provide generic functionality such as checking the
+#   host architecture, getting the host operating system, checking if a file
+#   exists, etc.
 #
-# These functions can be utilized to create precondition tests and test 
-# cases which require generic functionality that is not part of the
-# virt or web interface functions
+#   These functions can be utilized to create precondition tests and test 
+#   cases which require generic functionality that is not part of the
+#   virt or web interface functions
+#***
 #
 # =============================================================================
 
-# Simple function that checks if a file/folder exists
-# @param $1 - The location and name of the file
+
+#****f* general-interface/file_exists
+# NAME
+#   file_exists
+# DESCRIPTION
+#   Simple function that checks if a file/folder exists
+# ARGUMENTS
+#   $1 - The location and name of the file
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   file_exists ./template.xml
+#***
 file_exists()
 {
 	RESULT=1
@@ -29,8 +43,19 @@ file_exists()
 	return $RESULT
 }
 
-# Extracts a file based on extension within the directory it is located in
-# @param $1 - The location and name of the file
+
+#****f* general-interface/extract_file
+# NAME
+#   extract_file
+# DESCRIPTION
+#   Extracts a file based on extension within the directory it is located in
+# ARGUMENTS
+#   $1 - The location and name of the file
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   extract_file /root/file.tar.gz
+#***
 extract_file()
 {
 	RESULT=1
@@ -60,8 +85,19 @@ extract_file()
 	return $RESULT
 }
 
-# Function that returns the name of a file to be downloaded given a url
-# @param $1 - The download url of the file
+
+#****f* general-interface/filename_from_url
+# NAME
+#   filename_from_url
+# DESCRIPTION
+#   Function that returns the name of a file to be downloaded given a url
+# ARGUMENTS
+#   $1 - The download url of the file
+# RETURN VALUE
+#   filename - The name of a file to be downloaded
+# EXAMPLE
+#   FILE_NAME=$(filename_from_url http://someurl/file.tar.gz)
+#***
 filename_from_url()
 {
 	# Get the filename from location
@@ -70,9 +106,20 @@ filename_from_url()
 	echo ${FILENAME}
 }
 
-# Function that returns the name of a file to be downloaded given a url by
-# looking at the "Location:" specified in HTTP header
-# @param $1 - The download url of the file
+
+#****f* general-interface/filename_from_header
+# NAME
+#   filename_from_header
+# DESCRIPTION
+#   Function that returns the name of a file to be downloaded given a url by
+#   looking at the "Location:" specified in HTTP header
+# ARGUMENTS
+#   $1 - The download url of the file
+# RETURN VALUE
+#   filename - The name of a file to be downloaded
+# EXAMPLE
+#   FILE_NAME=$(filename_from_header http://someurl/file.tar.gz)
+#***
 filename_from_header()
 {
 	# Get the HTTP header with actual location of the file
@@ -85,10 +132,23 @@ filename_from_header()
 	echo ${FILENAME}
 }
 
-# Function that finds a file and returns the name and path of a file given the 
-# root directory and the extension of the file
-# @param $1	- The root directory to search for the file
-# @param $2 -The extension of the file to look for
+
+#****f* general-interface/find_file
+# NAME
+#   find_file
+# DESCRIPTION
+#   Function that finds a file and returns the name and path of a file given the 
+#   root directory and the extension of the file
+# ARGUMENTS
+#   $1 - The root directory to search for the file
+#   $2 - The extension of the file to look for
+# RETURN VALUE
+#   filelocation - The name and path of a file
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   FILE_LOCATION=$(find_file /usr/share/images vmdk)
+#***
 find_file()
 {
 	RESULT=1
@@ -101,10 +161,21 @@ find_file()
 	return $RESULT
 }
 
-# Simple function that returns the hash of a file
-# @param $1 - The location and name of the file
-# @param $2 - The type of hash, currently supported hashes are: 
-#			  crc32, md5, sha, sha1, sha224, sha256, sha384, sha512 
+
+#****f* general-interface/get_hash
+# NAME
+#   get_hash
+# DESCRIPTION
+#   Simple function that returns the hash of a file
+# ARGUMENTS
+#   $1 - The location and name of the file
+#   $2 - The type of hash, currently supported hashes are: 
+#        crc32, md5, sha, sha1, sha224, sha256, sha384, sha512
+# RETURN VALUE
+#   hash - The hash of the file
+# EXAMPLE
+#   HASH=$(get_hash /root/file.tar.gz md5)
+#***
 get_hash()
 {
 	HASH=""
@@ -140,8 +211,21 @@ get_hash()
 	echo ${HASH}
 }
 
-# Simple function that returns network name from xml network definition file
-# @param $1	- The network XML definition file
+
+#****f* general-interface/get_net_name
+# NAME
+#   get_net_name
+# DESCRIPTION
+#   Simple function that returns the network name from xml network definition file
+# ARGUMENTS
+#   $1 - The network XML definition file
+# RETURN VALUE
+#   networkname - The network name defined in the xml network definition file
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   NET_NAME=$(get_net_name ./network-definition.xml)
+#***
 get_net_name()
 {
 	RESULT=1
@@ -155,8 +239,21 @@ get_net_name()
 	return $RESULT	
 }
 
-# Simple function that returns ip address from xml network definition file
-# @param $1	- The network XML definition file
+
+#****f* general-interface/get_ip_address
+# NAME
+#   get_ip_address
+# DESCRIPTION
+#   Simple function that returns the ip address from the xml network definition file
+# ARGUMENTS
+#   $1 - The network XML definition file
+# RETURN VALUE
+#   ipaddress - The ip address defined in the xml network definition file
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   IP_ADDRESS=$(get_ip_address ./network-definition.xml)
+#***
 get_ip_address()
 {
 	RESULT=1
@@ -171,10 +268,20 @@ get_ip_address()
 }
 
 
-# A function which configures automatic SSH login using keys instead of passwords
-# @param $1 - The IP address of the machine to login via ssh
-# @param $2 - The username to login with
-# @param $3	- The password to login with
+#****f* general-interface/ssh_autologin
+# NAME
+#   ssh_autologin
+# DESCRIPTION
+#   A function which configures automatic SSH login using keys instead of passwords
+# ARGUMENTS
+#   $1 - The IP address of the machine to login via ssh
+#   $2 - The username to login with
+#   $3 - The password to login with
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   ssh_autologin 192.168.1.125 root password
+#***
 ssh_autologin()
 {
 	# Use a here-doc to script expect to automate password authentication
diff --git a/trunk/tapper/tapper-autoreport/virt-interface b/trunk/tapper/tapper-autoreport/virt-interface
--- a/trunk/tapper/tapper-autoreport/virt-interface
+++ b/trunk/tapper/tapper-autoreport/virt-interface
@@ -2,22 +2,35 @@
 
 # =============================================================================
 #
-# virt-interface
-# -----------------
+#****** test-suite/virt-interface
+# NAME
+#   virt-interface
 #
-# This script contains several virtualization functions that
-# interface with libvirsh and return a success or failure, 
-# which can be used to generate a TAP report.
+# DESCRIPTION
+#   This script contains several virtualization functions that
+#   interface with libvirsh and return a success or failure, 
+#   which can be used to generate a TAP report.
 #
-# These functions are well suited for precondition tests to ensure
-# that virtual machines can be created and controlled before 
-# executing any more tests.
+#   These functions are well suited for precondition tests to ensure
+#   that virtual machines can be created and controlled before 
+#   executing any more tests.
+#***
 #
 # =============================================================================
 
 
-# Set the default network as active and verify it is active
-# @param $1 - The virtual machine network name
+#****f* virt-interface/vm_net_active
+# NAME
+#   vm_net_active
+# DESCRIPTION
+#   Set the default network as active and verify it is active
+# ARGUMENTS
+#   $1 - The virtual machine network name
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   vm_net_active default
+#***
 vm_net_active()
 {	
 	virsh --connect $URI net-list --all | egrep -q "^$1[[:space:]]*active"
@@ -31,8 +44,19 @@ vm_net_active()
 	return $?
 }
 
-# Set the default network to autostart and verify that it is set to autostart
-# @param $1 - The virtual machine network name
+
+#****f* virt-interface/vm_net_autostart
+# NAME
+#   vm_net_autostart
+# DESCRIPTION
+#   Set the default network to autostart and verify that it is set to autostart
+# ARGUMENTS
+#   $1 - The virtual machine network name
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   vm_net_autostart default
+#***
 vm_net_autostart()
 {
 	virsh --connect $URI net-list --all | egrep -q "^$1[[:space:]]*active[[:space:]]*yes"
@@ -46,10 +70,22 @@ vm_net_autostart()
 	return $?
 }
 
-# Destroy a virtual machine network, verify it has been removed from virsh
-# NOTE: The network definition files will still exist, network is simply
-# 		no longer accesible until it is re-created 
-# @param $1 - The virtual machine network name
+
+#****f* virt-interface/destroy_vm_net
+# NAME
+#   destroy_vm_net
+# DESCRIPTION
+#   Destroy a virtual machine network, verify it has been removed from virsh
+# ARGUMENTS
+#   $1 - The virtual machine network name
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   destroy_vm_net default
+# NOTES
+#   The network definition files will still exist, network is simply no longer 
+#   accesible until it is re-created 
+#***
 destroy_vm_net()
 {
 	# First forecably shutdown the network
@@ -67,9 +103,20 @@ destroy_vm_net()
 	fi
 }
 
-# Create a virtual machine network from an xml file, verify it has been created 
-# @param $1 - The path to the network definition file
-# @param $2 - The virtual machine network name
+
+#****f* virt-interface/create_vm_net
+# NAME
+#   create_vm_net
+# DESCRIPTION
+#   Create a virtual machine network from an xml file, verify it has been created 
+# ARGUMENTS
+#   $1 - The path to the network definition file
+#   $2 - The virtual machine network name
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   create_vm_net ./network-definition.xml default
+#***
 create_vm_net()
 {
 	virsh --connect $URI net-define $1
@@ -78,9 +125,20 @@ create_vm_net()
 	return $?
 }
 
-# Create a virtual machine from an xml file, verify it has been created 
-# @param $1 - The path to the virtual machine definition file
-# @param $2 - The name of the virtual machine
+
+#****f* virt-interface/create_vm
+# NAME
+#   create_vm
+# DESCRIPTION
+#   Create a virtual machine from an xml file, verify it has been created 
+# ARGUMENTS
+#   $1 - The path to the virtual machine definition file
+#   $2 - The name of the virtual machine
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   create_vm ./vm-definition.xml virt-machine
+#***
 create_vm()
 {
 	virsh --connect $URI define $1
@@ -89,10 +147,22 @@ create_vm()
 	return $?
 }
 
-# Destroy a virtual machine, verify it has been removed from virsh
-# NOTE: The files will still exist, the virtual machine is simply
-# 		no longer accesible until it is re-created 
-# @param $1 - The name of the virtual machine
+
+#****f* virt-interface/destroy_vm
+# NAME
+#   destroy_vm
+# DESCRIPTION
+#   Destroy a virtual machine, verify it has been removed from virsh
+# ARGUMENTS
+#   $1 - The name of the virtual machine
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   destroy_vm virt-machine
+# NOTES
+#   The files will still exist, the virtual machine is simply no longer 
+#   accesible until it is re-created 
+#***
 destroy_vm()
 {
 	# First forecably shutdown the virtual machine
@@ -110,8 +180,19 @@ destroy_vm()
 	fi
 }
 
-# Start the virtual machine and verify it started
-# @param $1 - The name of the virtual machine
+
+#****f* virt-interface/start_vm
+# NAME
+#   start_vm
+# DESCRIPTION
+#   Start the virtual machine and verify it started
+# ARGUMENTS
+#   $1 - The name of the virtual machine
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   start_vm virt-machine
+#***
 start_vm()
 {	
 	virsh --connect $URI start $1
@@ -122,8 +203,19 @@ start_vm()
 	return $?
 }
 
-# Stop the virtual machine and verify it has shutdown
-# @param $1 - The name of the virtual machine
+
+#****f* virt-interface/stop_vm
+# NAME
+#   stop_vm
+# DESCRIPTION
+#   Stop the virtual machine and verify it has shutdown
+# ARGUMENTS
+#   $1 - The name of the virtual machine
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   stop_vm virt-machine
+#***
 stop_vm()
 {
 	virsh --connect $URI shutdown $1
@@ -134,12 +226,23 @@ stop_vm()
 	return $?
 }
 
-# TODO: ADD SUPPORT TO VERIFY LOGIN THROUGH TTY CONSOLE
-# 		LOOKS RELATIVELY FEASIBLE USING
-#		http://search.cpan.org/~cosimo/Device-Modem-1.54/
-# Verify that the virtual machine has console support
-# requires that the virtual machine has been first started
-# @param $1 - The name of the virtual machine
+
+#****f* virt-interface/has_console_support
+# NAME
+#   has_console_support
+# DESCRIPTION
+#   Verify that the virtual machine has console support requires that the virtual
+#   machine has been first started
+# ARGUMENTS
+#   $1 - The name of the virtual machine
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   has_console_support virt-machine
+# WARNINGS
+#   Support for this function has been deprecated and its use is strongly
+#   discouraged as console support is unnecessary and only supported for KVM
+#***
 has_console_support()
 {
 	virsh --connect $URI ttyconsole $1
@@ -147,8 +250,19 @@ has_console_support()
 	return $?
 }
 
-# Connect to virsh for the current virtual machine hypervisor URI and display URI
-# @param $1 - The URI of the hypervisor
+
+#****f* virt-interface/connect_virsh
+# NAME
+#   connect_virsh
+# DESCRIPTION
+#   Connect to virsh for the current virtual machine hypervisor URI and display URI
+# ARGUMENTS
+#   $1 - The URI of the hypervisor
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   connect_virsh qemu:///system
+#***
 connect_virsh()
 {
 	virsh -q --connect $1 uri
