SUMMARY: A large list of changes and improvements made to the scipts, everything that was discussed during a previous meeting last week has been implemented, the scripts have been re-structured and there is now a clearly readable and coloured trace output logfile by default
ADD: Added trace support for success, errors, and generic messages, all tests are now logged in the trace output logfile and are clearly readable and coloured

ADD: Added support to the tapper-autoreport functions ok() and notok() which adds support for all precondition tests and test cases to be logged in the trace output logfile


git-svn-id: http://cernvm-release-testing.googlecode.com/svn@195 e1b191a7-760c-b37a-3d11-b84f7cd3b9c7

diff --git a/trunk/tapper/tapper-autoreport/testsuite-trace b/trunk/tapper/tapper-autoreport/testsuite-trace
--- a/trunk/tapper/tapper-autoreport/testsuite-trace
+++ b/trunk/tapper/tapper-autoreport/testsuite-trace
@@ -261,6 +261,27 @@ log_trace_output()
     done
 }
 
+#****f* testsuite-trace/log_trace_message
+# NAME
+#   log_trace_message
+# DESCRIPTION
+#   Logs the generic,error,and success trace messages to file
+# ARGUMENTS
+#   $1 - The name of the logfile to store the trace message
+#   $2 - The actual messsage to store in the logfile
+# RESULT
+#   exitstatus - Sets $? as a zero for success, otherwise sets an error code
+# EXAMPLE
+#   log_trace_output $TRACE_LOGFILE "SUCCESS - Test Case Executed Without Errors"
+#***
+log_trace_message()
+{
+    # TODO: Add support for indenting the message based on the scope
+    #       depth (for when trace verbosity level 3 is used)
+    # Log the message to the trace logfile
+    echo -e "$2" >> $1
+}
+
 
 #****f* testsuite-trace/create_trace_log
 # NAME
@@ -358,6 +379,12 @@ reset_scope()
 #***
 success_msg()
 {
+    # If the trace verbosity level is set higher than 1, log message
+    if [ "$TRACE_VERBOSITY" -gt 1 ]
+    then
+        log_trace_message $TRACE_LOGFILE "\e[0;32mSUCCESS - ${1}\e[0m"
+    fi
+
     return 0
 }
 
@@ -376,6 +403,12 @@ success_msg()
 #***
 error_msg()
 {
+    # If the trace verbosity level is set higher than 0, log message
+    if [ "$TRACE_VERBOSITY" -gt 0 ]
+    then
+        log_trace_message $TRACE_LOGFILE "\e[0;31mFAILURE - ${1}\e[0m"
+    fi
+
     return 0
 }
 
@@ -394,7 +427,13 @@ error_msg()
 #***
 generic_msg()
 {
-    return
+    # If the trace verbosity level is set higher than 1, log message
+    if [ "$TRACE_VERBOSITY" -gt 1 ]
+    then
+        log_trace_message $TRACE_LOGFILE "\e[0;36m${1}\e[0m"
+    fi
+
+    return 0
 }
 
 
